# Etapa de build
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o wishlist ./cmd/server

# Etapa final
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/wishlist /app/wishlist
COPY .env /app/.env

EXPOSE 8080
CMD ["./wishlist"]
