# Etapa de build
FROM golang:1.25 AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux go build -o server ./cmd/server

# Etapa final
FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/server .
COPY --from=builder /app/.env .

EXPOSE 8080
CMD ["./server"]
