// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Search books using Google Books API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.GoogleBook"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List registered users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.User"
                            }
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/wishlist": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wishlist"
                ],
                "summary": "List all wishlists for a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.Wishlist"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wishlist"
                ],
                "summary": "Create a new wishlist",
                "parameters": [
                    {
                        "description": "Wishlist data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CreateWishlistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/wishlist/{id}": {
            "delete": {
                "tags": [
                    "wishlist"
                ],
                "summary": "Delete a wishlist by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wishlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/wishlist/{id}/books": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List all books from a wishlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wishlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.Book"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Add a book to the wishlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wishlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Book data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.AddBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/wishlist/{id}/books/{bookID}": {
            "delete": {
                "tags": [
                    "books"
                ],
                "summary": "Remove a book from a wishlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wishlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "bookID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_deividmendozatech-stack_wishlist_internal_service.Book": {
            "type": "object",
            "properties": {
                "author": {
                    "description": "Book author",
                    "type": "string"
                },
                "id": {
                    "description": "Auto-increment primary key",
                    "type": "integer"
                },
                "title": {
                    "description": "Book title",
                    "type": "string"
                },
                "wishlistID": {
                    "description": "Reference to the parent wishlist",
                    "type": "integer"
                }
            }
        },
        "github_com_deividmendozatech-stack_wishlist_internal_service.GoogleBook": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_deividmendozatech-stack_wishlist_internal_service.User": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Auto-increment primary key",
                    "type": "integer"
                },
                "password": {
                    "description": "Hashed password",
                    "type": "string"
                },
                "username": {
                    "description": "Unique username",
                    "type": "string"
                }
            }
        },
        "github_com_deividmendozatech-stack_wishlist_internal_service.Wishlist": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Auto-increment primary key",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the wishlist",
                    "type": "string"
                },
                "userID": {
                    "description": "Reference to the owning user",
                    "type": "integer"
                }
            }
        },
        "internal_handler.AddBookRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Antoine de Saint-Exupéry"
                },
                "title": {
                    "type": "string",
                    "example": "The Little Prince"
                }
            }
        },
        "internal_handler.CreateWishlistRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "My book list"
                }
            }
        },
        "internal_handler.RegisterUserRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "1234"
                },
                "username": {
                    "type": "string",
                    "example": "david"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
