definitions:
  github_com_deividmendozatech-stack_wishlist_internal_service.Book:
    properties:
      author:
        description: Book author
        type: string
      id:
        description: Auto-increment primary key
        type: integer
      title:
        description: Book title
        type: string
      wishlistID:
        description: Reference to the parent wishlist
        type: integer
    type: object
  github_com_deividmendozatech-stack_wishlist_internal_service.GoogleBook:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
  github_com_deividmendozatech-stack_wishlist_internal_service.User:
    properties:
      id:
        description: Auto-increment primary key
        type: integer
      password:
        description: Hashed password
        type: string
      username:
        description: Unique username
        type: string
    type: object
  github_com_deividmendozatech-stack_wishlist_internal_service.Wishlist:
    properties:
      id:
        description: Auto-increment primary key
        type: integer
      name:
        description: Name of the wishlist
        type: string
      userID:
        description: Reference to the owning user
        type: integer
    type: object
  internal_handler.AddBookRequest:
    properties:
      author:
        example: Antoine de Saint-Exupéry
        type: string
      title:
        example: The Little Prince
        type: string
    type: object
  internal_handler.CreateWishlistRequest:
    properties:
      name:
        example: My book list
        type: string
    type: object
  internal_handler.RegisterUserRequest:
    properties:
      password:
        example: "1234"
        type: string
      username:
        example: david
        type: string
    type: object
info:
  contact: {}
paths:
  /books/search:
    get:
      parameters:
      - description: Search term
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.GoogleBook'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Search books using Google Books API
      tags:
      - books
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.User'
            type: array
      summary: List registered users
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Register a new user
      tags:
      - users
  /wishlist:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.Wishlist'
            type: array
      summary: List all wishlists for a user
      tags:
      - wishlist
    post:
      consumes:
      - application/json
      parameters:
      - description: Wishlist data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CreateWishlistRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create a new wishlist
      tags:
      - wishlist
  /wishlist/{id}:
    delete:
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete a wishlist by ID
      tags:
      - wishlist
  /wishlist/{id}/books:
    get:
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_deividmendozatech-stack_wishlist_internal_service.Book'
            type: array
      summary: List all books from a wishlist
      tags:
      - books
    post:
      consumes:
      - application/json
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handler.AddBookRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add a book to the wishlist
      tags:
      - books
  /wishlist/{id}/books/{bookID}:
    delete:
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book ID
        in: path
        name: bookID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Remove a book from a wishlist
      tags:
      - books
swagger: "2.0"
